### ISSUE TITLE
Display the conversations instead of the list of user within the sidebar

### ISSUE THREAD

**Issue by Grace-Endy** [StyvenSoft/Chat-platform#3]
Is there a way to display the existing conversations instead of the list of user? Because, for instance if we have 5000 users, that would have no sense to display all the users within the sidebar, having a conversation table, which would contain users relationship(I mean users who have started any conversation in the past),  that would be much more easier.

**Comment by StyvenSoft** [comment]
In the case of this chat, it is not convenient to show only the conversations that a user has, since it is a global chat where you can interact with all registered users, but you could limit the number of users in the [Users component](https://github.com/StyvenSoft/Chat-platform/blob/main/client/src/pages/Home/Users.js).
Although in the same way it is only a local practice project since I use: 
```
sequelize seed: generate --name create-users 
```
to create [test users](https://github.com/StyvenSoft/Chat-platform/blob/main/seeders/20210119040741-create-users.js).

However thank you very much for the suggestion.
